### ISSUE TITLE
Wrong definition of registers in `gdb/features/tricore.c`

### ISSUE THREAD

**Issue by alexandersohn** [NoMore201/tricore-gdb#1]
Hey,

in thanks for maintaining this version of gdb that supports tricore. When using this build I had problems reading all registers. I think the reason for this is a duplicate definition of the `lcx` register in `gdb/features/tricore.c`. 

The reason for this duplicate definition is in line 13713 of the 0006-Rebase-tricore-implementation-from-10.0.50-to-11.2.patch patch file. Would you be willing to accept a PR to fix this issue?

**Comment by NoMore201** [comment]
Hello! Sure you can go on with a PR, thanks for reporting

**Comment by NoMore201** [comment]
Solved by PR #2
